version: '3.9'

services:
  # Servizio per il Database MySQL
  db:
    image: mysql:8.0
    container_name: it_authentication_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: it_authentication
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: authpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  # Servizio per phpMyAdmin (opzionale)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - db

  # Servizio per il Backend (BE) con Spring Boot
  backend:
    image: openjdk:17-jdk-slim
    container_name: it_authentication_be
    ports:
      - "8081:8080"  # Mappa la porta 8080 del container alla porta 8081 sulla macchina host
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ./target:/app
    command: ["java", "-jar", "/app/it_authentication_be-1.0-SNAPSHOT.jar"]

volumes:
  db_data:
